Repository codesquad-members-2023/second-hand, pull requests merged in 2023-06, with the labels that each got.

#6 [team-04] README 업데이트 (팀원 및 팀 저장소 등록)
  README.md
Labels: documentation

#23 [team-03] iOS 프로젝트를 생성하였습니다
  iOS/.gitignore
  iOS/Second-Hand/.swiftlint.yml
  iOS/Second-Hand/Second-Hand.xcodeproj/project.pbxproj
  iOS/Second-Hand/Second-Hand.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/Second-Hand/Second-Hand.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/Second-Hand/Second-Hand/Application/AppDelegate.swift
  iOS/Second-Hand/Second-Hand/Application/SceneDelegate.swift
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Info.plist
  iOS/Second-Hand/Second-Hand/UI/Home/ViewController/HomeViewController.swift
  iOS/Second-Hand/Second-Hand/UI/Launch/View/Base.lproj/LaunchScreen.storyboard
Labels: review-ios

#14 [team-04] iOS: 프로젝트 설정 및 초기 작업
  .github/workflows/auto_deploy.yml
  README.md
  ios/.gitignore
  ios/Daangn/.swiftlint.yml
  ios/Daangn/Daangn.xcodeproj/project.pbxproj
  ios/Daangn/Daangn.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/Daangn/Daangn.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Daangn/Daangn/Global/Literal/ColorStyle.swift
  ios/Daangn/Daangn/Global/Literal/FontStyle.swift
  ios/Daangn/Daangn/Global/Literal/ImageMapper.swift
  ios/Daangn/Daangn/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/black.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/blue.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/gray100.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/gray200.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/gray300.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/gray400.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/gray50.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/gray500.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/gray600.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/gray700.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/gray800.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/gray900.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/mint.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/orange.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/red.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Color/white.colorset/Contents.json
  ios/Daangn/Daangn/Resource/Assets.xcassets/Contents.json
  ios/Daangn/Daangn/Supporting Files/AppDelegate.swift
  ios/Daangn/Daangn/Supporting Files/Base.lproj/LaunchScreen.storyboard
  ios/Daangn/Daangn/Supporting Files/Base.lproj/Main.storyboard
  ios/Daangn/Daangn/Supporting Files/Info.plist
  ios/Daangn/Daangn/Supporting Files/SceneDelegate.swift
Labels: review-ios

#24 [team-05] 프로젝트 초기 설정 & 전반적인 설계
  .github/workflows/publish.yml
  backend/.gitignore
  backend/Dockerfile
  backend/Dockerfile-nginx
  backend/build.gradle
  backend/docker-compose.yml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/nginx/conf.d/nginx.conf
  backend/settings.gradle
  backend/src/main/java/com/team5/secondhand/BackendApplication.java
  backend/src/main/java/com/team5/secondhand/global/config/ApiDocsConfig.java
  backend/src/main/java/com/team5/secondhand/global/config/WebConfig.java
  backend/src/main/java/com/team5/secondhand/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/team5/secondhand/global/exception/dto/ErrorResponse.java
  backend/src/main/java/com/team5/secondhand/temp/controller/TestApiController.java
  backend/src/main/java/com/team5/secondhand/temp/dto/PostRequest.java
  backend/src/main/java/com/team5/secondhand/temp/dto/PostResponse.java
  backend/src/main/resources/application-db-local.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/schema.sql
  backend/src/test/java/com/team5/secondhand/BackendApplicationTests.java
Labels: review-be

#27 [TEAM-06] FE 1주차 PR
  .github/ISSUE_TEMPLATE/-이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/fe-release.yml
  README.md
  appspec.yml
  fe/.eslintignore
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/craco.config.js
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.tsx
  fe/src/assets/arrowUp.svg
  fe/src/assets/camera.svg
  fe/src/assets/chevronDown.svg
  fe/src/assets/chevronLeft.svg
  fe/src/assets/circleFill.svg
  fe/src/assets/ellipsis.svg
  fe/src/assets/hamburger.svg
  fe/src/assets/home.svg
  fe/src/assets/keyboard.svg
  fe/src/assets/like.svg
  fe/src/assets/message.svg
  fe/src/assets/multiply.svg
  fe/src/assets/newspaper.svg
  fe/src/assets/person.svg
  fe/src/assets/plus.svg
  fe/src/assets/search.svg
  fe/src/components/ProductListItem/index.tsx
  fe/src/components/ProductListItem/style.ts
  fe/src/components/common/Icon/index.tsx
  fe/src/context/themeContext.tsx
  fe/src/hooks/useFetch.ts
  fe/src/hooks/useIntersectionObserver.ts
  fe/src/index.tsx
  fe/src/pages/Home/index.tsx
  fe/src/pages/Home/style.ts
  fe/src/pages/NeighborhoodSetting/index.tsx
  fe/src/pages/NeighborhoodSetting/style.ts
  fe/src/react-app-env.d.ts
  fe/src/reportWebVitals.ts
  fe/src/setupTests.ts
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/color.ts
  fe/src/styles/font.ts
  fe/tsconfig.json
  fe/tsconfig.paths.json
  scripts/ApplicationStart.sh
Labels: review-fe

#19 [team-01] BE 1주차 초기 설정 및 설계
  .idea/.gitignore
  .idea/git_toolbox_prj.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/second-hand.iml
  .idea/vcs.xml
  BE/.gitignore
  BE/.idea/.gitignore
  BE/.idea/.name
  BE/.idea/compiler.xml
  BE/.idea/jarRepositories.xml
  BE/.idea/vcs.xml
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/codesquad/secondhand/SecondHandApplication.java
  BE/src/main/java/codesquad/secondhand/config/JasyptConfig.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/test/java/codesquad/secondhand/SecondHandApplicationTests.java
  README.md
Labels: review-be

#28 [team-05] iOS - 프로젝트 준비 및 초기화면 UI 구현
  iOS/.gitignore
  iOS/second-hand/Podfile
  iOS/second-hand/Podfile.lock
  iOS/second-hand/second-hand.xcodeproj/project.pbxproj
  iOS/second-hand/second-hand.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/second-hand/second-hand.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/second-hand/second-hand.xcodeproj/project.xcworkspace/xcuserdata/hwajin.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/second-hand/second-hand.xcodeproj/xcuserdata/hwajin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/second-hand/second-hand/Application/AppDelegate.swift
  iOS/second-hand/second-hand/Application/SceneDelegate.swift
  iOS/second-hand/second-hand/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/second-hand/second-hand/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/second-hand/second-hand/Assets.xcassets/Contents.json
  iOS/second-hand/second-hand/Assets.xcassets/threeLines.imageset/Contents.json
  iOS/second-hand/second-hand/Assets.xcassets/threeLines.imageset/Label.png
  iOS/second-hand/second-hand/Base.lproj/LaunchScreen.storyboard
  iOS/second-hand/second-hand/CategoriesScrollView.swift
  iOS/second-hand/second-hand/CategoryButton.swift
  iOS/second-hand/second-hand/Chatting/ChattingViewController.swift
  iOS/second-hand/second-hand/Home/ButtonCustomView.swift
  iOS/second-hand/second-hand/Home/Controller/HomeViewController.swift
  iOS/second-hand/second-hand/Home/HomeLeftBarButton.swift
  iOS/second-hand/second-hand/Home/HomeRightBarButton.swift
  iOS/second-hand/second-hand/Info.plist
  iOS/second-hand/second-hand/MyAccount/Controller/IdStackView.swift
  iOS/second-hand/second-hand/MyAccount/Controller/MyAccountViewController.swift
  iOS/second-hand/second-hand/NavigationUnderLineViewController.swift
  iOS/second-hand/second-hand/SaleLog/Controller/SaleLogViewController.swift
  iOS/second-hand/second-hand/SaleLog/View/SaleLogNavigationView.swift
  iOS/second-hand/second-hand/TabBarControl/NavigationUnderLineViewController.swift
  iOS/second-hand/second-hand/TabBarControl/SecondHandTabBarController.swift
  iOS/second-hand/second-hand/TabBarControl/TabBarItem.swift
  iOS/second-hand/second-hand/UIExtensions/UIColor+Extension.swift
  iOS/second-hand/second-hand/UIExtensions/UIFont+Extension.swift
  iOS/second-hand/second-hand/WishListViewController.swift
Labels: review-ios

#17 [team-04] FE: 1주차 PR
  README.md
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/craco.config.js
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.test.tsx
  fe/src/App.tsx
  fe/src/assets/arrowUp.svg
  fe/src/assets/camera.svg
  fe/src/assets/chevronDown.svg
  fe/src/assets/chevronLeft.svg
  fe/src/assets/circleFill.svg
  fe/src/assets/ellipsis.svg
  fe/src/assets/heart.svg
  fe/src/assets/home.svg
  fe/src/assets/index.tsx
  fe/src/assets/keyboard.svg
  fe/src/assets/line.svg
  fe/src/assets/message.svg
  fe/src/assets/multiply.svg
  fe/src/assets/newspaper.svg
  fe/src/assets/person.svg
  fe/src/assets/plus.svg
  fe/src/assets/search.svg
  fe/src/assets/slider.svg
  fe/src/components/common/Icon.tsx
  fe/src/constants/index.ts
  fe/src/hooks/useFetch/index.tsx
  fe/src/hooks/useFetch/useFetch.test.ts
  fe/src/index.tsx
  fe/src/styles/GlobalStyle.tsx
  fe/src/styles/color.tsx
  fe/src/styles/font.tsx
  fe/src/types/global/custom.d.ts
  fe/tsconfig.json
  fe/tsconfig.paths.json
Labels: review-fe

#12 [BE][TEAM-04: NINO, Hyun] 1주차 PR
  be/README.md
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/team4/codesquad/secondhand/BeApplication.java
  be/src/main/java/team4/codesquad/secondhand/configuration/WebConfig.java
  be/src/main/java/team4/codesquad/secondhand/constant/ResponseMessage.java
  be/src/main/java/team4/codesquad/secondhand/constant/Status.java
  be/src/main/java/team4/codesquad/secondhand/constant/StatusCode.java
  be/src/main/java/team4/codesquad/secondhand/controller/ProductController.java
  be/src/main/java/team4/codesquad/secondhand/domain/Category.java
  be/src/main/java/team4/codesquad/secondhand/domain/Chatroom.java
  be/src/main/java/team4/codesquad/secondhand/domain/Location.java
  be/src/main/java/team4/codesquad/secondhand/domain/Product.java
  be/src/main/java/team4/codesquad/secondhand/domain/ProductImage.java
  be/src/main/java/team4/codesquad/secondhand/domain/User.java
  be/src/main/java/team4/codesquad/secondhand/domain/Watchlist.java
  be/src/main/java/team4/codesquad/secondhand/domain/dto/Message.java
  be/src/main/java/team4/codesquad/secondhand/domain/dto/ProductDTO.java
  be/src/main/java/team4/codesquad/secondhand/domain/dto/ProductListDTO.java
  be/src/main/java/team4/codesquad/secondhand/repository/CategoryRepository.java
  be/src/main/java/team4/codesquad/secondhand/repository/ChatroomRepository.java
  be/src/main/java/team4/codesquad/secondhand/repository/LocationRepository.java
  be/src/main/java/team4/codesquad/secondhand/repository/ProductImageRepository.java
  be/src/main/java/team4/codesquad/secondhand/repository/ProductRepository.java
  be/src/main/java/team4/codesquad/secondhand/repository/UserRepository.java
  be/src/main/java/team4/codesquad/secondhand/repository/WatchRepository.java
  be/src/main/java/team4/codesquad/secondhand/service/ProductService.java
  be/src/test/java/team4/codesquad/secondhand/BeApplicationTests.java
Labels: review-be

#16 [team-05] FE 초기 환경 설정
  front-end/.eslintrc.json
  front-end/.gitignore
  front-end/.prettierrc
  front-end/.storybook/main.ts
  front-end/.storybook/preview.ts
  front-end/index.html
  front-end/package.json
  front-end/public/favicon.ico
  front-end/src/App.tsx
  front-end/src/assets/Icon.tsx
  front-end/src/assets/svgs/arrowUp.svg
  front-end/src/assets/svgs/camera.svg
  front-end/src/assets/svgs/chevronDown.svg
  front-end/src/assets/svgs/chevronLeft.svg
  front-end/src/assets/svgs/circleFill.svg
  front-end/src/assets/svgs/ellipsis.svg
  front-end/src/assets/svgs/hamburger.svg
  front-end/src/assets/svgs/heart.svg
  front-end/src/assets/svgs/home.svg
  front-end/src/assets/svgs/index.ts
  front-end/src/assets/svgs/keyboard.svg
  front-end/src/assets/svgs/location.svg
  front-end/src/assets/svgs/message.svg
  front-end/src/assets/svgs/newspaper.svg
  front-end/src/assets/svgs/person.svg
  front-end/src/assets/svgs/plus.svg
  front-end/src/assets/svgs/search.svg
  front-end/src/assets/svgs/svg.d.ts
  front-end/src/assets/svgs/x.svg
  front-end/src/components/common/Button/index.ts
  front-end/src/components/common/Chip/index.ts
  front-end/src/components/common/Dropdown/index.ts
  front-end/src/components/common/ImgBox/index.ts
  front-end/src/components/common/Item/index.ts
  front-end/src/components/common/NavBar/index.ts
  front-end/src/components/common/TabBar/index.ts
  front-end/src/main.tsx
  front-end/src/pages/Login.tsx
  front-end/src/styles/colors.ts
  front-end/src/styles/fonts.ts
  front-end/src/styles/globalStyles.ts
  front-end/src/styles/styled.d.ts
  front-end/src/styles/theme.ts
  front-end/src/vite-env.d.ts
  front-end/tsconfig.json
  front-end/tsconfig.node.json
  front-end/vite.config.ts
Labels: review-fe

#21 [team-03] FE 1주차 설계 및 초기 환경 설정
  conf/nginx/nginx.conf
  frontend/.eslintignore
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierrc
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/assets/arrowUp.svg
  frontend/src/assets/camera.svg
  frontend/src/assets/chevronDown.svg
  frontend/src/assets/chevronLeft.svg
  frontend/src/assets/circleFill.svg
  frontend/src/assets/ellipsis.svg
  frontend/src/assets/hamburger.svg
  frontend/src/assets/heart.svg
  frontend/src/assets/home.svg
  frontend/src/assets/keyboard.svg
  frontend/src/assets/message.svg
  frontend/src/assets/newspaper.svg
  frontend/src/assets/person.svg
  frontend/src/assets/plus.svg
  frontend/src/assets/search.svg
  frontend/src/assets/slider.svg
  frontend/src/assets/x.svg
  frontend/src/components/App/index.tsx
  frontend/src/index.tsx
  frontend/src/styles/GlobalStyles.tsx
  frontend/src/styles/theme.ts
  frontend/tsconfig.json
  package-lock.json
Labels: review-fe

#44 [team-03] 회원가입 화면 UI를 구현 하였습니다
  .github/ISSUE_TEMPLATE/team03-second-hand.md
  README.md
  iOS/Second-Hand/Second-Hand.xcodeproj/project.pbxproj
  iOS/Second-Hand/Second-Hand/Application/SceneDelegate.swift
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/black.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/blue.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/gray100.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/gray200.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/gray300.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/gray400.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/gray50.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/gray500.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/gray600.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/gray700.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/gray800.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/gray900.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/mint.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/orange.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/red.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/Resource/Assets.xcassets/Colors/white.colorset/Contents.json
  iOS/Second-Hand/Second-Hand/UI/Account/Constant/IDInputView+Constant.swift
  iOS/Second-Hand/Second-Hand/UI/Account/Constant/ImageSelectButton+Constant.swift
  iOS/Second-Hand/Second-Hand/UI/Account/Constant/LocationAddButton+Constant.swift
  iOS/Second-Hand/Second-Hand/UI/Account/Constant/SignUpViewController+Constant.swift
  iOS/Second-Hand/Second-Hand/UI/Account/View/IDInputView.swift
  iOS/Second-Hand/Second-Hand/UI/Account/View/ImageSelectButton.swift
  iOS/Second-Hand/Second-Hand/UI/Account/View/LocationAddButton.swift
  iOS/Second-Hand/Second-Hand/UI/Account/ViewController/SignUpViewController.swift
  iOS/Second-Hand/Second-Hand/UI/Common/ColorPalette.swift
  iOS/Second-Hand/Second-Hand/UI/Common/FontStyle.swift
  iOS/Second-Hand/Second-Hand/UI/Common/ViewController/SecondHandTabBarController.swift
Labels: review-ios

#37 [team-05] 홈, 로그인 구현
  front-end/.gitignore
  front-end/.storybook/main.ts
  front-end/.storybook/preview.ts
  front-end/package.json
  front-end/src/App.tsx
  front-end/src/api.ts
  front-end/src/assets/svgs/svg.d.ts
  front-end/src/components/common/Button/Button.tsx
  front-end/src/components/common/Button/index.ts
  front-end/src/components/common/Chip/Chip.tsx
  front-end/src/components/common/Chip/index.ts
  front-end/src/components/common/Dropdown/index.ts
  front-end/src/components/common/ImgBox/ImgBox.tsx
  front-end/src/components/common/ImgBox/index.ts
  front-end/src/components/common/Item/Item.tsx
  front-end/src/components/common/Item/index.ts
  front-end/src/components/common/NavBar/NavBar.tsx
  front-end/src/components/common/NavBar/index.ts
  front-end/src/components/common/PopupSheet/PopupSheet.tsx
  front-end/src/components/common/PopupSheet/index.ts
  front-end/src/components/common/Spinner/Spinner.tsx
  front-end/src/components/common/TabBar/ChatTabBar.tsx
  front-end/src/components/common/TabBar/MainTabBar.tsx
  front-end/src/components/common/TabBar/SubTabBar.tsx
  front-end/src/components/common/TabBar/TabBar.tsx
  front-end/src/components/common/TabBar/index.ts
  front-end/src/components/common/Textarea/Textarea.tsx
  front-end/src/components/common/Textarea/index.ts
  front-end/src/components/home/ItemList/ItemList.tsx
  front-end/src/components/home/ItemList/index.ts
  front-end/src/constants/popupSheetMenu.ts
  front-end/src/hooks/useInput.tsx
  front-end/src/hooks/useIntersectionObserver.tsx
  front-end/src/pages/ChatList.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/Layout.tsx
  front-end/src/pages/Login.tsx
  front-end/src/pages/MyAccount.tsx
  front-end/src/pages/SalesHistory.tsx
  front-end/src/pages/WishList.tsx
  front-end/src/routes/AppRouter.tsx
  front-end/src/styles/globalStyles.ts
  front-end/src/utils/formatNumberToSI.ts
  front-end/tsconfig.json
  front-end/vite.config.ts
Labels: review-fe

#39 [team-04] iOS: 홈, 판매 내역, 관심 상품 화면 및 상품 리스트 컴포넌트, 로그인 화면 컴포넌트 구현
  ios/Daangn/Daangn.xcodeproj/project.pbxproj
  ios/Daangn/Daangn/CategoryFilter/CategoryFilterCollectionView.swift
  ios/Daangn/Daangn/CategoryFilter/CategoryFilterCollectionViewCell.swift
  ios/Daangn/Daangn/CategoryFilter/CateogryFilterDataSource.swift
  ios/Daangn/Daangn/Common/Radius.swift
  ios/Daangn/Daangn/Component/BorderView.swift
  ios/Daangn/Daangn/Component/IDField.swift
  ios/Daangn/Daangn/Component/LoginButton.swift
  ios/Daangn/Daangn/Component/PaddedLabel.swift
  ios/Daangn/Daangn/Component/ProductListImageView.swift
  ios/Daangn/Daangn/Component/ProductStateBadge.swift
  ios/Daangn/Daangn/Component/ProfileImageButton.swift
  ios/Daangn/Daangn/Component/TownButton.swift
  ios/Daangn/Daangn/Controller/CategoryViewController.swift
  ios/Daangn/Daangn/Controller/ChatViewController.swift
  ios/Daangn/Daangn/Controller/ConfigureTown.swift
  ios/Daangn/Daangn/Controller/CreateAccountViewController.swift
  ios/Daangn/Daangn/Controller/HomeViewController.swift
  ios/Daangn/Daangn/Controller/MyAccountViewController.swift
  ios/Daangn/Daangn/Controller/SalesViewController.swift
  ios/Daangn/Daangn/Controller/SellHistoryViewController.swift
  ios/Daangn/Daangn/Controller/WatchlistViewController.swift
  ios/Daangn/Daangn/Extension/CollectionViewLayout+layouts.swift
  ios/Daangn/Daangn/Extension/UILabel+style.swift
  ios/Daangn/Daangn/Extension/UIView+Radius.swift
  ios/Daangn/Daangn/Global/TabBarController.swift
  ios/Daangn/Daangn/Model/Category.swift
  ios/Daangn/Daangn/Model/ProductState.swift
  ios/Daangn/Daangn/ProductList/LoadCollectionViewCell.swift
  ios/Daangn/Daangn/ProductList/ProductListCollectionView.swift
  ios/Daangn/Daangn/ProductList/ProductListCollectionViewCell.swift
  ios/Daangn/Daangn/ProductList/ProductListDataSource.swift
  ios/Daangn/Daangn/Supporting Files/Base.lproj/Main.storyboard
  ios/Daangn/Daangn/Supporting Files/Info.plist
  ios/Daangn/Daangn/Supporting Files/SceneDelegate.swift
Labels: review-ios

#47 [team-2] iOS 2주차 PR
  ios/SecondHand/SecondHand.xcodeproj/project.pbxproj
  ios/SecondHand/SecondHand/FontStyle.swift
  ios/SecondHand/SecondHand/Home/HomeViewController.swift
  ios/SecondHand/SecondHand/Home/ProductTableViewCell.swift
  ios/SecondHand/SecondHand/Network/NetworkManager.swift
  ios/SecondHand/SecondHand/Profile/InputView.swift
  ios/SecondHand/SecondHand/Profile/OrangeButton.swift
  ios/SecondHand/SecondHand/Profile/ProfileImageView.swift
  ios/SecondHand/SecondHand/Profile/ProfileViewController.swift
  ios/SecondHand/SecondHand/Profile/SeparatorView.swift
  ios/SecondHand/SecondHand/Profile/SignInViewController.swift
  ios/SecondHand/SecondHand/Profile/SignUpViewController.swift
  ios/SecondHand/SecondHand/SupportingFiles/Info.plist
Labels: review-ios

#48 [Team-02] BE 2주차 PR 입니다. re
  .github/workflows/main.yml
  be/Dockerfile
  be/Dockerfile-nginx
  be/build.gradle
  be/docker-compose.yml
  be/nginx/conf.d/nginx.conf
  be/src/main/java/com/secondhand/config/WebConfig.java
  be/src/main/java/com/secondhand/domain/board/BoardController.java
  be/src/main/java/com/secondhand/domain/categorie/Category.java
  be/src/main/java/com/secondhand/domain/categorie/CategoryRepository.java
  be/src/main/java/com/secondhand/domain/exception/ElementNotFoundException.java
  be/src/main/java/com/secondhand/domain/exception/GlobalExceptionHandler.java
  be/src/main/java/com/secondhand/domain/exception/NoSuchElementFoundException.java
  be/src/main/java/com/secondhand/domain/interested/Interested.java
  be/src/main/java/com/secondhand/domain/member/Member.java
  be/src/main/java/com/secondhand/domain/member/MemberRepository.java
  be/src/main/java/com/secondhand/domain/member/MemberService.java
  be/src/main/java/com/secondhand/domain/product/CountInfo.java
  be/src/main/java/com/secondhand/domain/product/MemberProduct.java
  be/src/main/java/com/secondhand/domain/product/Product.java
  be/src/main/java/com/secondhand/domain/product/ProductImage.java
  be/src/main/java/com/secondhand/domain/product/ProductRepository.java
  be/src/main/java/com/secondhand/domain/product/ProductService.java
  be/src/main/java/com/secondhand/domain/product/Status.java
  be/src/main/java/com/secondhand/domain/town/TownRepository.java
  be/src/main/java/com/secondhand/domain/town/TownService.java
  be/src/main/java/com/secondhand/domain/town/Towns.java
  be/src/main/java/com/secondhand/oauth/GitHubOauth.java
  be/src/main/java/com/secondhand/oauth/Oauth.java
  be/src/main/java/com/secondhand/oauth/dto/AccessTokenResponseDTO.java
  be/src/main/java/com/secondhand/oauth/dto/OAuthMemberInfoDTO.java
  be/src/main/java/com/secondhand/oauth/dto/req/AccessTokenRequestBodyDTO.java
  be/src/main/java/com/secondhand/oauth/exception/AccessTokenNotFoundException.java
  be/src/main/java/com/secondhand/oauth/exception/GitHubRequestException.java
  be/src/main/java/com/secondhand/oauth/exception/OAuthException.java
  be/src/main/java/com/secondhand/oauth/service/GiHubService.java
  be/src/main/java/com/secondhand/oauth/service/JwtService.java
  be/src/main/java/com/secondhand/util/BaseTimeEntity.java
  be/src/main/java/com/secondhand/util/Message.java
  be/src/main/java/com/secondhand/util/ResponseEntity.java
  be/src/main/java/com/secondhand/web/contoroller/CategoryController.java
  be/src/main/java/com/secondhand/web/contoroller/MemberController.java
  be/src/main/java/com/secondhand/web/contoroller/ProductController.java
  be/src/main/java/com/secondhand/web/contoroller/TownController.java
  be/src/main/java/com/secondhand/web/dto/req/FilterRequestDTO.java
  be/src/main/java/com/secondhand/web/dto/req/ProductLikeResponseDTO.java
  be/src/main/java/com/secondhand/web/dto/req/ProductSaveRequestDTO.java
  be/src/main/java/com/secondhand/web/dto/req/ProductUpdateRequestDTO.java
  be/src/main/java/com/secondhand/web/dto/resp/BoardsDTOResponse.java
  be/src/main/java/com/secondhand/web/dto/resp/CategoryDTo.java
  be/src/main/java/com/secondhand/web/dto/resp/MemberLoginResponseDTO.java
  be/src/main/java/com/secondhand/web/dto/resp/MemberTownInfoResponseDTO.java
  be/src/main/java/com/secondhand/web/dto/resp/ProductDTO.java
  be/src/main/java/com/secondhand/web/dto/resp/ProductResponseDTO.java
  be/src/main/java/com/secondhand/web/dto/resp/TownDTO.java
  be/src/main/java/com/secondhand/web/dto/resp/TownsListResponseDTO.java
  be/src/main/resources/application-prod.yml
  be/src/main/resources/data.sql
Labels: review-be

#43 [Team-05] FE 2주차 리뷰
  fe/.eslintrc.json
  fe/.storybook/main.ts
  fe/.storybook/preview.tsx
  fe/craco.config.js
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/ProductList/index.tsx
  fe/src/components/ProductList/style.ts
  fe/src/components/ProductListItem/index.tsx
  fe/src/components/ProductListItem/style.ts
  fe/src/components/TabBar/index.tsx
  fe/src/components/TabBar/style.ts
  fe/src/components/common/Button/index.tsx
  fe/src/components/common/Button/style.ts
  fe/src/components/common/Header/index.tsx
  fe/src/components/common/Header/style.ts
  fe/src/components/common/Icon/index.tsx
  fe/src/constants/index.ts
  fe/src/context/themeContext.tsx
  fe/src/hooks/useFetch.ts
  fe/src/hooks/useIntersectionObserver.ts
  fe/src/pages/Category/index.tsx
  fe/src/pages/Chatting/index.tsx
  fe/src/pages/Home/index.tsx
  fe/src/pages/Interests/index.tsx
  fe/src/pages/MyAccount/index.tsx
  fe/src/pages/MyAccount/style.ts
  fe/src/pages/Oauth.tsx
  fe/src/pages/Sales/index.tsx
  fe/src/styles/color.ts
  fe/src/utils/index.tsx
Labels: review-fe

#49 [team-05] iOS 2주차 PR입니다 :)
  iOS/second-hand/second-hand.xcodeproj/project.pbxproj
  iOS/second-hand/second-hand/CategoryButton.swift
  iOS/second-hand/second-hand/CategoryScrollView.swift
  iOS/second-hand/second-hand/Chatting/Controller/ChattingViewController.swift
  iOS/second-hand/second-hand/Home/ButtonCustomView.swift
  iOS/second-hand/second-hand/Home/Controller/HomeViewController.swift
  iOS/second-hand/second-hand/Home/HomeLeftBarButton.swift
  iOS/second-hand/second-hand/MyAccount/Controller/LoginMyAccountViewController.swift
  iOS/second-hand/second-hand/MyAccount/Controller/NotLoginMyAccountViewController.swift
  iOS/second-hand/second-hand/MyAccount/SubScene/Controller/GithubWebViewController.swift
  iOS/second-hand/second-hand/MyAccount/SubScene/Controller/JoinViewController.swift
  iOS/second-hand/second-hand/MyAccount/View/IdStackView.swift
  iOS/second-hand/second-hand/NavigationUnderLineViewController.swift
  iOS/second-hand/second-hand/Network/GitUser+Region.swift
  iOS/second-hand/second-hand/Network/HTTPErrors.swift
  iOS/second-hand/second-hand/Network/HTTPMethod.swift
  iOS/second-hand/second-hand/Network/JSONCreater.swift
  iOS/second-hand/second-hand/Network/NetworkManager.swift
  iOS/second-hand/second-hand/SaleLog/Controller/SaleLogViewController.swift
  iOS/second-hand/second-hand/TabBarControl/SecondHandTabBarController.swift
  iOS/second-hand/second-hand/UIExtensions/UIColor+Extension.swift
  iOS/second-hand/second-hand/WishListViewController.swift
Labels: review-ios

#36 [Team-01] fe 리뷰 2주차
  fe/.gitignore
  fe/.storybook/style.css
  fe/package.json
  fe/pnpm-lock.yaml
  fe/public/index.html
  fe/src/assets/icons/index.ts
  fe/src/components/commons/BottomSheet/BottomSheet.stories.tsx
  fe/src/components/commons/BottomSheet/BottomSheet.tsx
  fe/src/components/commons/BottomSheet/BottomSheetStyle.ts
  fe/src/components/commons/Button/Button.tsx
  fe/src/components/commons/Button/ButtonStyle.ts
  fe/src/components/commons/Dialog/Dialog.stories.tsx
  fe/src/components/commons/Dialog/Dialog.tsx
  fe/src/components/commons/Dialog/DialogStyle.ts
  fe/src/components/commons/Icon/IconStyle.ts
  fe/src/components/commons/InfoBar/InfoBarStyle.ts
  fe/src/components/commons/ListItem/ListItem.stories.ts
  fe/src/components/commons/ListItem/ListItem.tsx
  fe/src/components/commons/ListItem/ListItemStyle.ts
  fe/src/components/commons/NavBar/NavBar.tsx
  fe/src/components/commons/NavBar/NavBarStyle.ts
  fe/src/components/commons/NavBar/Navbar.stories.tsx
  fe/src/components/commons/Profile/Profile.tsx
  fe/src/components/commons/Slide/Slide.stories.ts
  fe/src/components/commons/Slide/Slide.tsx
  fe/src/components/commons/Slide/SlidePageIndicator/SlidePageIndicator.tsx
  fe/src/components/commons/Slide/SlidePageIndicator/SlidePageIndicatorStyle.ts
  fe/src/components/commons/Slide/SlideStyle.ts
  fe/src/components/commons/SnackBar/SnackBar.stories.tsx
  fe/src/components/commons/SnackBar/SnackBar.tsx
  fe/src/components/commons/SnackBar/SnackBarStyle.ts
  fe/src/components/commons/Tab/Tab.stories.tsx
  fe/src/components/commons/Tab/Tab.tsx
  fe/src/components/commons/TabBar/TabBar.stories.ts
  fe/src/components/commons/TabBar/TabBar.tsx
  fe/src/components/commons/TabBar/TabBarStyle.ts
  fe/src/components/commons/TextInput/TextInput.tsx
  fe/src/components/commons/TextInput/TextInputStyle.ts
  fe/src/components/commons/index.ts
  fe/src/services/slide.ts
  fe/src/styles/GlobalStyle.ts
Labels: review-fe

#63 [team05] iOS 3주차 PR입니다
  iOS/second-hand/second-hand.xcodeproj/project.pbxproj
  iOS/second-hand/second-hand/CategoryButton.swift
  iOS/second-hand/second-hand/CategoryScrollView.swift
  iOS/second-hand/second-hand/Home/ButtonCustomView.swift
  iOS/second-hand/second-hand/Home/Controller/HomeViewController.swift
  iOS/second-hand/second-hand/Home/HomeLeftBarButton.swift
  iOS/second-hand/second-hand/Home/HomeRightBarButton.swift
  iOS/second-hand/second-hand/Home/View/HomeProductCollectionViewCell.swift
  iOS/second-hand/second-hand/Home/subScene/RegisterNewProduct/Model/ImageRequest.swift
  iOS/second-hand/second-hand/Home/subScene/RegisterNewProduct/Model/ProductPicture.swift
  iOS/second-hand/second-hand/Home/subScene/RegisterNewProduct/RegisterNewProductViewController.swift
  iOS/second-hand/second-hand/Home/subScene/RegisterNewProduct/View/ProductImage.swift
  iOS/second-hand/second-hand/Home/subScene/RegisterNewProduct/View/RegisterProductScrollVeiw.swift
  iOS/second-hand/second-hand/Home/subScene/SetLocation/Controller/SetLocationViewController.swift
  iOS/second-hand/second-hand/MyAccount/Controller/LoginMyAccountViewController.swift
  iOS/second-hand/second-hand/MyAccount/Controller/NotLoginMyAccountViewController.swift
  iOS/second-hand/second-hand/MyAccount/SubScene/GithubWeb/Controller/GithubWebViewController.swift
  iOS/second-hand/second-hand/MyAccount/SubScene/Join/Controller/JoinViewController.swift
  iOS/second-hand/second-hand/MyAccount/View/IdStackView.swift
  iOS/second-hand/second-hand/NavigationUnderLineViewController.swift
  iOS/second-hand/second-hand/Network/CodableTemplate.swift
  iOS/second-hand/second-hand/Network/HTTPErrors.swift
  iOS/second-hand/second-hand/Network/JSONCreater.swift
  iOS/second-hand/second-hand/Network/NetworkManager.swift
  iOS/second-hand/second-hand/Network/Server.swift
  iOS/second-hand/second-hand/TabBarControl/SecondHandTabBarController.swift
  iOS/second-hand/second-hand/TabBarControl/TabBarItem.swift
  iOS/second-hand/second-hand/UIExtensions/UIButton+Extension.swift
  iOS/second-hand/second-hand/UIExtensions/UIImageView+Extension.swift
  iOS/second-hand/second-hand/UIExtensions/UITextField+Extension.swift
  iOS/second-hand/second-hand/UIExtensions/UIView+Extension.swift
Labels: review-ios

#66 [team-03] 프로필 이미지 사진을 변경할 수 있도록 구현하였습니다
  iOS/Second-Hand/Second-Hand.xcodeproj/project.pbxproj
  iOS/Second-Hand/Second-Hand/UI/Account/Constant/ProfileImageView+Constant.swift
  iOS/Second-Hand/Second-Hand/UI/Account/View/ImageSelectButton.swift
  iOS/Second-Hand/Second-Hand/UI/Account/View/ProfileImageView.swift
  iOS/Second-Hand/Second-Hand/UI/Account/ViewController/SignUpViewController.swift
  iOS/Second-Hand/Second-Hand/UI/Common/ViewController/SecondHandTabBarController.swift
Labels: review-ios

#67 [team-01] iOS: 로그인 UI 구현 및 2주차 리뷰 반영
  iOS/SecondHand/SecondHand.xcodeproj/project.pbxproj
  iOS/SecondHand/SecondHand/Detail/DetailContentView+layoutConstraint.swift
  iOS/SecondHand/SecondHand/Detail/DetailContentView.swift
  iOS/SecondHand/SecondHand/Detail/DetailViewController+layoutScrollView.swift
  iOS/SecondHand/SecondHand/Detail/DetailViewController.swift
  iOS/SecondHand/SecondHand/Detail/SellerInfo.swift
  iOS/SecondHand/SecondHand/Detail/UI/CommunicationInfo.swift
  iOS/SecondHand/SecondHand/Detail/UI/DetailContentView.swift
  iOS/SecondHand/SecondHand/Detail/UI/DetailToolbar.swift
  iOS/SecondHand/SecondHand/Detail/UI/ProductInfo.swift
  iOS/SecondHand/SecondHand/Detail/UI/SellerInfo.swift
  iOS/SecondHand/SecondHand/Factory/AccountButtonUIFactory.swift
  iOS/SecondHand/SecondHand/ItemList/IssueListItem.swift
  iOS/SecondHand/SecondHand/ItemList/ItemListTableViewCell.swift
  iOS/SecondHand/SecondHand/ItemList/ItemListViewController.swift
  iOS/SecondHand/SecondHand/ItemList/Network.swift
  iOS/SecondHand/SecondHand/ItemList/View/CapsuleLabel.swift
  iOS/SecondHand/SecondHand/ItemList/View/LeadingIconLabel.swift
  iOS/SecondHand/SecondHand/ItemList/View/LocationLabel.swift
  iOS/SecondHand/SecondHand/ItemList/View/PriceLabel.swift
  iOS/SecondHand/SecondHand/ItemList/View/TimeLabel.swift
  iOS/SecondHand/SecondHand/ItemList/View/TitleLabel.swift
  iOS/SecondHand/SecondHand/Login/LoginViewController.swift
  iOS/SecondHand/SecondHand/Login/UI/AccountInputView.swift
  iOS/SecondHand/SecondHand/Login/UI/LoginButtonGroupView+addAction.swift
  iOS/SecondHand/SecondHand/Login/UI/LoginButtonGroupView.swift
  iOS/SecondHand/SecondHand/ShareComponent/ColorPalette.swift
  iOS/SecondHand/SecondHand/ShareComponent/Typography.swift
  iOS/SecondHand/SecondHand/ShareComponent/UIFont+Typography.swift
  iOS/SecondHand/SecondHand/Tabbar/TabBarController.swift
  iOS/SecondHand/SecondHand/Tabbar/TabBarType.swift
  iOS/SecondHand/SecondHand/ViewController.swift
Labels: review-ios

#64 [team-04] iOS: 로그인 기능 구현
  ios/.gitignore
  ios/Daangn/.swiftlint.yml
  ios/Daangn/Daangn.xcodeproj/project.pbxproj
  ios/Daangn/Daangn/CategoryCollection/CategoryCollectionViewCell.swift
  ios/Daangn/Daangn/CategoryFilter/CategoryFilterCollectionView.swift
  ios/Daangn/Daangn/CategoryFilter/CategoryFilterCollectionViewCell.swift
  ios/Daangn/Daangn/Common/DTO.swift
  ios/Daangn/Daangn/Common/JWToken.swift
  ios/Daangn/Daangn/Common/NetworkError.swift
  ios/Daangn/Daangn/Common/NetworkManager.swift
  ios/Daangn/Daangn/Common/SignUpTempInfo.swift
  ios/Daangn/Daangn/Component/BorderView.swift
  ios/Daangn/Daangn/Component/CollectionViewLayoutGenerator.swift
  ios/Daangn/Daangn/Component/IDField.swift
  ios/Daangn/Daangn/Component/LoginButton.swift
  ios/Daangn/Daangn/Component/ProductListImageView.swift
  ios/Daangn/Daangn/Component/ProductStateBadge.swift
  ios/Daangn/Daangn/Component/ProfileImageButton.swift
  ios/Daangn/Daangn/Component/TownButton.swift
  ios/Daangn/Daangn/Controller/CategoryViewController.swift
  ios/Daangn/Daangn/Controller/ConfigureTown.swift
  ios/Daangn/Daangn/Controller/CreateAccountViewController.swift
  ios/Daangn/Daangn/Controller/HomeViewController.swift
  ios/Daangn/Daangn/Controller/MyAccountViewController.swift
  ios/Daangn/Daangn/Controller/SalesViewController.swift
  ios/Daangn/Daangn/Controller/SearchTownController.swift
  ios/Daangn/Daangn/Controller/SellHistoryViewController.swift
  ios/Daangn/Daangn/Controller/WatchlistViewController.swift
  ios/Daangn/Daangn/Model/Category.swift
  ios/Daangn/Daangn/Model/TempTownArray.swift
  ios/Daangn/Daangn/ProductList/LoadCollectionViewCell.swift
  ios/Daangn/Daangn/ProductList/ProductListCollectionView.swift
Labels: review-ios
